
services:

  app:
    build: .
    ports:
      - 8080:8080
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

  # cockroachdb:
  #   image: cockroachdb
  #   ports:
  #     - 26257:26257
  #   restart: always