
services:

  # app:
  #   build: .
  #   ports:
  #     - 8080:8080
  #   restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: always

  cockroachdb:
    image: cockroachdb/cockroach:latest
    container_name: roach1
    ports:
      - 26257:26257
      - 8080:8080
    restart: always
    command:
      - "start"
      - "--insecure"
      # - "--certs-dir=/certs"
      - "--advertise-addr=:26257"
      - "--http-addr=:8080"
      - "--join=roach1:26257"
    volumes:
      - ./roach1_data:/cockroach/cockroach-data
      # - ./certs:/certs

  db:
    image: postgres:14.7-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_INITDB_ARGS: "--locale=ru_RU"
    ports:
      - 5432:5432
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s